
visu.ui.title=VISU
visu.ui.stylesheet=/css/style.css
visu.ui.width=1024
visu.ui.height=600

visu.engine.layout.damping=0.9
visu.engine.forces.repulsion.strength=50000.0
visu.engine.forces.repulsion.minDistance=20.0
visu.engine.forces.attraction.strength=0.05
visu.engine.forces.attraction.restLength=300.0
visu.engine.forces.gravity.strength=0.01
visu.engine.forces.gravity.centerX=200.0
visu.engine.forces.gravity.centerY=250.0